### ISSUE TITLE
Practice tests

### ISSUE THREAD

**Issue by itdeveloper50** [ajfuto/comptia-security-plus#1]
Hello!

Thank you for sharing useful information with us.
I am also preparing for this exam.

Could you share Jason Dion practice tests book with me?

Thank you.

**Comment by ajfuto** [comment]
No. Please buy [Dion's practice tests](https://www.udemy.com/course/security-601-exams/) -- they are well worth it. If you don't want to dish out the money now, wait till they go on sale (they frequently do). If you want free practice tests, look at the ExamCompass link I posted.
